Repository codeit-sprint-part4-8-1/codeit_8_1, pull requests merged in 2024-10, with the labels that each got.

#3 chore: 프리티어추가
  .prettierrc.json
Labels: chore 💼

#5 Feat: 메인 페이지 공통 컴포넌트 제작
  .vscode/settings.json
  package-lock.json
  package.json
  postcss.config.mjs
  public/ico/ico_twitter.svg
  src/components/@Shared/Buttons/LogoButton.tsx
  src/components/@Shared/Container.tsx
  src/components/@Shared/Footer.tsx
  src/components/@Shared/GNB.tsx
  src/pages/_app.tsx
  src/pages/index.tsx
  src/styles/globals.css
  tailwind.config.ts
Labels: Feature ✨

#6 Feat 프로필 메뉴 구현
  .gitignore
  next.config.mjs
  package-lock.json
  package.json
  public/ico/ico_history.svg
  public/ico/ico_management.svg
  public/ico/ico_myInfo.svg
  public/ico/ico_pen.svg
  public/ico/ico_status.svg
  public/image/defaultProfile.webp
  src/apis/instance/axiosInstance.ts
  src/apis/myInfo/api.ts
  src/components/myPage/ProfileMenu.tsx
  src/pages/myInfo/index.tsx
  src/types/myPage/type.ts
Labels: Feature ✨

#7 Feat 공통 컴포넌트 드롭다운 메뉴 구현
  package-lock.json
  package.json
  src/components/@Shared/dropDown/DropDownMenu.tsx
Labels: Feature ✨

#8 Feat: 메인페이지 카테고리 구현
  src/components/@Shared/category/MainCategory.tsx
  src/styles/globals.css
Labels: Feature ✨

#9 feat: 카테고리 드롭다운 컴포넌트 제작
  package-lock.json
  package.json
  src/components/@Shared/dropdown/Dropdown.tsx
Labels: Feature ✨

#11 Feat: 메인페이지 검색창 구현
  package-lock.json
  src/components/@Shared/searchBar/SearchBar.tsx
  src/styles/globals.css
  tailwind.config.ts
Labels: Feature ✨

#10 feat: Pretendard 로컬 폰트 다운로드 및 전역 적용
  public/fonts/PretendardVariable.woff2
  src/styles/globals.css
  tailwind.config.ts
Labels: etc 🎸

#13 Feat f81 43 캘린더버튼
  package-lock.json
  package.json
  src/components/@Shared/calender/calender.tsx
Labels: Feature ✨

#16 Feat: F81-45 체험등록페이지 작업
  package-lock.json
  package.json
  src/components/@Shared/dropdown/Dropdown.tsx
  src/pages/_document.tsx
  src/pages/myInfo/activites.tsx
Labels: Feature ✨

#14 Feat f81 46 공용버튼
  package-lock.json
  package.json
  src/components/@Shared/Buttons/Button.tsx
  src/styles/globals.css
Labels: Feature ✨

#18 Feat: 내 정보 페이지 구현
  package-lock.json
  package.json
  public/ico/ico_history.svg
  public/ico/ico_historyActive.svg
  public/ico/ico_management.svg
  public/ico/ico_managementActive.svg
  public/ico/ico_myInfo.svg
  public/ico/ico_myInfoActive.svg
  public/ico/ico_status.svg
  public/ico/ico_statusActive.svg
  src/apis/instance/axiosInstance.ts
  src/apis/myInfo/api.ts
  src/components/@Shared/Container.tsx
  src/components/@Shared/profileMenu/ProfileMenu.tsx
  src/components/myInfo/MyInfoForm.tsx
  src/hook/useProfileImage.ts
  src/pages/_app.tsx
  src/pages/_document.tsx
  src/pages/myInfo/index.tsx
  src/types/myPage/type.ts
  src/utils/myInfoValidation.ts
Labels: Feature ✨, Refactor ⚙️

#20 Feat: 예약내역페이지
  package-lock.json
  package.json
  public/ico/ico_check.svg
  src/components/@Shared/Buttons/Button.tsx
  src/components/@Shared/dropDown/DropDownMenu.tsx
  src/components/@Shared/modal/ConfirmModal.tsx
  src/components/@Shared/modal/ModalFrame.tsx
  src/components/@Shared/profileMenu/ProfileMenu.tsx
  src/hook/useInfiniteScroll.tsx
  src/hook/useUserInfo.tsx
  src/pages/_app.tsx
  src/pages/history/index.tsx
  src/pages/myInfo/index.tsx
  tailwind.config.ts
  tsconfig.json
Labels: Feature ✨, Refactor ⚙️

#22 Feat: #F81-13 후기작성모달
  public/ico/ico_close.svg
  public/ico/ico_star.svg
  src/components/@Shared/Buttons/Button.tsx
  src/components/@Shared/modal/ReviewModal.tsx
  src/components/myInfo/MyInfoForm.tsx
  src/hook/useUserInfo.tsx
Labels: Feature ✨, Refactor ⚙️

#23 feat:F81-48체험등록페이지구현
  src/pages/activities/activities.tsx
  src/pages/activities/detail.tsx
Labels: Feature ✨

#21 Feat : F81-51-로그인 기능 구현 및 기타 작업
  package-lock.json
  src/apis/instance/axiosInstance.ts
  src/apis/myInfo/api.ts
  src/components/@Shared/Buttons/Button.tsx
  src/components/auth/AuthDtos.ts
  src/components/auth/AuthInput.tsx
  src/components/auth/LoginForm.tsx
  src/components/auth/Modal.tsx
  src/components/auth/PasswordHide.tsx
  src/components/auth/SignUpForm.tsx
  src/components/auth/Validations.ts
  src/components/auth/modalClose.ts
Labels: fix 🔨, Feature ✨, etc 🎸
