Repository codeit-sprint-part4-8-1/codeit_8_1, pull requests merged in 2024-11, with the labels that each got.

#28 Feat: 예약내역api연동
  public/image/defaultImage.png
  public/image/notDataImage.png
  src/apis/myInfo/api.ts
  src/components/@Shared/modal/ConfirmModal.tsx
  src/components/@Shared/modal/ModalFrame.tsx
  src/components/@Shared/modal/ReviewModal.tsx
  src/hook/useInfiniteScroll.tsx
  src/hook/useObserverScroll.tsx
  src/hook/useUserInfo.tsx
  src/pages/history/index.tsx
  src/types/myPage/type.ts
Labels: Feature ✨

#25 Feat : F81-52 로그인 회원가입 퍼블리싱 완료 및 반응형 적용
  package-lock.json
  public/ico/ico_google.svg
  public/ico/ico_kakaotalk.svg
  src/components/@Shared/Container.tsx
  src/components/auth/AuthBottom.tsx
  src/components/auth/AuthContainer.tsx
  src/components/auth/AuthInput.tsx
  src/components/auth/AuthLogo.tsx
  src/components/auth/LoginForm.tsx
  src/pages/login/index.tsx
  src/pages/signup/index.tsx
  tailwind.config.ts
Labels: Refactor ⚙️, etc 🎸

#29 Feat: f81-5 예약 현황 페이지 구현
  src/components/@Shared/dropDown/StatusDropdown.tsx
  src/components/status/ReservationStatusSkeleton.tsx
  src/components/status/StatusCalendar.tsx
  src/pages/status/index.tsx
Labels: Feature ✨

#30 feat: F81-71 리프레시 토큰 구현
  src/apis/instance/axiosInstance.ts
Labels: Feature ✨

#31 Feat: 메인페이지 인기 체험 카드와 목록 제작
  .vscode/settings.json
  public/ico/ico_arrow_left_active.svg
  public/ico/ico_arrow_left_inactive.svg
  public/ico/ico_arrow_right_active.svg
  public/ico/ico_arrow_right_inactive.svg
  public/image/mainBanner04.png
  public/image/mainBanner05.png
  public/image/mainBanner06.png
  public/image/mainBanner07.png
  public/image/mainBanner08.png
  public/image/mainBanner09.png
  public/image/mainBanner10.png
  src/components/@Shared/searchBar/SearchBar.tsx
  src/components/mainPage/HotActivityCard.tsx
  src/components/mainPage/HotActivityList.tsx
  src/components/mainPage/HotActivityListData.ts
  src/pages/index.tsx
  src/types/mainPage/HotActivityCardTypes.ts
Labels: Feature ✨

#32 Feat: 예약 내역 필터 구현과 반응형 구현
  package-lock.json
  package.json
  public/ico/ico_backArrow.svg
  src/apis/myInfo/api.ts
  src/components/@Shared/Buttons/Button.tsx
  src/components/@Shared/MoContainer.tsx
  src/components/@Shared/dropDown/DropDownMenu.tsx
  src/components/@Shared/loading/LoadingSpinner.tsx
  src/components/@Shared/modal/ConfirmModal.tsx
  src/components/@Shared/modal/ModalFrame.tsx
  src/components/@Shared/modal/ReviewModal.tsx
  src/components/@Shared/profileMenu/ProfileMenu.tsx
  src/components/history/NotData.tsx
  src/components/history/ReservationCard.tsx
  src/components/history/ReservationList.tsx
  src/components/history/ReservationSkeletonCard.tsx
  src/components/myInfo/BackButton.tsx
  src/components/myInfo/MyInfoForm.tsx
  src/hook/useUserInfo.tsx
  src/pages/history/index.tsx
  src/pages/myInfo/index.tsx
  src/styles/globals.css
  src/types/myPage/type.ts
  src/utils/reservationValidation.ts
Labels: Feature ✨, Refactor ⚙️

#33 Feat: 메인 페이지 레이아웃 제작
  src/components/@Shared/Footer.tsx
  src/components/mainPage/ActivityList.tsx
  src/components/mainPage/Category&DropDown.tsx
  src/pages/index.tsx
Labels: Feature ✨, Refactor ⚙️

#36 Feat: f81-78 예약 현황 페이지 데이터 연동
  src/apis/status/myActivitiesQueryOption.ts
  src/apis/status/myActivitiesService.ts
  src/apis/status/useMyActivitiesService.ts
  src/components/@Shared/dropDown/StatusDropdown.tsx
  src/components/@Shared/toast/Toast.tsx
  src/components/@Shared/toast/ToastType.ts
  src/components/@Shared/toast/ToastUi.tsx
  src/components/status/StatusCalendar.tsx
  src/components/status/StatusCalendarSkeleton.tsx
  src/components/status/StatusHistory.tsx
  src/components/status/StatusModal.tsx
  src/components/status/StatusModalLayout.tsx
  src/hook/useModal.tsx
  src/pages/_document.tsx
  src/pages/status/index.tsx
  src/types/status/myActivitiesType.ts
Labels: fix 🔨, Feature ✨

#37 Feat: 체험 상세 후기 리스트 구현
  src/apis/detail/api.ts
  src/components/detail/ReviewList.tsx
Labels: Feature ✨

#34 feat:F81-73체험등록페이지 API연동작업
  package-lock.json
  package.json
  src/components/@Shared/dropdown/Dropdown.tsx
  src/pages/activities/activities.tsx
  src/pages/activities/detail.tsx
Labels: fix 🔨, Feature ✨

#35 feat: F81-72 Root Context 제작 및 헤더 수정
  src/components/@Shared/GNB.tsx
  src/components/auth/AuthDtos.ts
  src/components/auth/LoginForm.tsx
  src/hook/useRoot.tsx
  src/pages/_app.tsx
  src/pages/login/index.tsx
Labels: fix 🔨, Feature ✨, Refactor ⚙️, etc 🎸

#38 Feat: 모든 체험 목록 API 연동
  .vscode/settings.json
  package-lock.json
  src/components/@Shared/category/MainCategory.tsx
  src/components/mainPage/ActivityCard.tsx
  src/components/mainPage/ActivityList.tsx
  src/components/mainPage/ActivityListData.ts
  src/components/mainPage/Category&DropDown.tsx
  src/pages/activity/[id].tsx
  src/pages/index.tsx
Labels: Feature ✨, Refactor ⚙️

#39 Feat: 체험상세미리보기구현
  public/ico/ico_point.svg
  public/image/mapTestImage.png
  src/apis/detail/api.ts
  src/components/detail/Description.tsx
  src/components/detail/Preview.tsx
  src/components/detail/ReviewList.tsx
  src/pages/detail/[id].tsx
  src/types/detailPage/type.ts
Labels: Feature ✨

#40 feat:F81-79 수정하기 기능추가
  package-lock.json
  package.json
  src/pages/activities/activities.tsx
  src/pages/activities/detail.tsx
  src/pages/activities/edit/[experienceId].tsx
Labels: Feature ✨

#41 Feat: f81-80 예약 현황 페이지 내비게이션 연동
  src/pages/myInfo/index.tsx
  src/pages/status/index.tsx
Labels: fix 🔨, Refactor ⚙️

#42 Feat f81 82 gnb수정및알람기능추가
  public/ico/ico_blueDot.svg
  public/ico/ico_redDot.svg
  public/ico/ico_smallClose.svg
  public/ico/ico_smallCloseGray.svg
  src/components/@Shared/Container.tsx
  src/components/@Shared/GNB.tsx
  src/components/auth/LoginForm.tsx
  src/components/gnb/Nickname.tsx
  src/components/gnb/ProfileImage.tsx
  src/components/notifications/NotificationBox.tsx
  src/components/notifications/notificationsQueryOption.ts
  src/components/notifications/notificationsService.ts
  src/components/notifications/notificationsType.ts
  src/components/notifications/useNotificationsService.ts
  src/hook/useRoot.tsx
  src/pages/_app.tsx
Labels: fix 🔨, Feature ✨

#43 Feat: 체험 정렬 순서 드롭다운 기능 구현
  src/components/@Shared/category/MainCategory.tsx
  src/components/@Shared/dropDown/DropDownMenu.tsx
  src/components/@Shared/dropdown/Dropdown.tsx
  src/components/mainPage/ActivityCard.tsx
  src/components/mainPage/ActivityList.tsx
  src/components/mainPage/Category&DropDown.tsx
  src/pages/index.tsx
Labels: Feature ✨, Refactor ⚙️

#44 feat: 81-81 체험등록페이지 오류수정 및 무한스크롤 추가
  src/components/activities/activities.tsx
  src/components/activities/detail.tsx
  src/components/activities/edit/[experienceId].tsx
  src/pages/myInfo/index.tsx
Labels: fix 🔨, Feature ✨

#45 Feat: 체험상세 수정하기 기능 구현과 예약하기 기능 구현
  package-lock.json
  package.json
  src/apis/detail/api.ts
  src/apis/instance/axiosInstance.ts
  src/components/@Shared/profileMenu/ProfileMenuLink.tsx
  src/components/activities/activities.tsx
  src/components/activities/detail.tsx
  src/components/detail/Preview.tsx
  src/components/detail/ReserveCalendar.tsx
  src/components/detail/ReviewList.tsx
  src/components/history/ReservationCard.tsx
  src/components/history/ReservationList.tsx
  src/components/mainPage/ActivityCard.tsx
  src/components/myInfo/BackButton.tsx
  src/pages/activities/activities.tsx
  src/pages/activities/edit/[experienceId].tsx
  src/pages/activity/[id].tsx
  src/pages/detail/[id].tsx
  src/pages/myInfo/index.tsx
  src/pages/status/index.tsx
  src/styles/globals.css
  src/types/detailPage/type.ts
  src/types/myPage/type.ts
Labels: Feature ✨
